routes/web.php
<?php


use  GuzzleHttp\Client ;
use Illuminate\Support\Facades\Input;
use App\Colonias;
use App\Citys;
use App\CatCiudades;


Route::get('download-jsonfile', array('as'=> 'file.download', 'uses' => 'TestController@downloadJSONFile'));



Route::get('/samples/document/txt/sample3.txt', 'TestController@ticket'); // listado

Route::get('/test/prueba.txt', 'TestController@test'); // listado

Route::get('/', 'TestController@welcome');
Route::get('/kowiEstadio/{id}', 'TestController@welcomeEstadio');
Route::get('/reportar', 'TestController@reporteerror');
Route::post('/reportar', 'TestController@reporteerrorcreate');


//api de la app en expo
Route::post('/curlNotification','NotificacionesFirebase@curlNotification');
Route::get('/productos1', 'apiController@productos1');






Auth::routes();




    //vendor package route files alymosul/laravel-exponent-push-notifications/Http/routes.php exluded in package.json
    //this is override alymosul/laravel-exponent-push-notifications/Http/routes.php
    //for suit middleware
	Route::group(['prefix' => 'api/exponent/devices', 'middleware' => ['bindings']], function () { 
	    Route::post('subscribe', [
	        'as'    =>  'register-interest',
	        'uses'  =>  'NotificationChannels\ExpoPushNotifications\Http\ExpoController@subscribe',
	    ]);

	    Route::post('unsubscribe', [
	        'as'    =>  'remove-interest',
	        'uses'  =>  'NotificationChannels\ExpoPushNotifications\Http\ExpoController@unsubscribe',
	    ]);
	});
 
 
Route::get('/ajax-colonias',function(){
	
	$cit_id = Input::get('cit_id');

	$colonias = CatCiudades::where('ciudad', '=', $cit_id)->distinct()->get(['codigopostal']);

	return Response::json($colonias);
});


Route::get('/ajax-codigoPostales',function(){
	
	$col_id = Input::get('col_id');

	$colonias =CatCiudades::where('codigopostal', '=', $col_id)->distinct()->get(['colonia']);

	return Response::json($colonias);
});


Route::get('/json-api', function() {
	$client = new Client();

	$response = $client->request('GET', 'http://appkowi.kowi.com.mx/home');
	$statusCode = $response->getStatusCode();
	$body = $response->getBody()->getContents();

	if ($statusCode === 200 ) {
        return View::make('pago');
    }

	return $statusCode;
});

Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');

Route::get('/live_search2/action', 'LiveSearch2@action')->name('live_search2.action');

Route::get('/live_search3/action', 'LiveSearch3@action')->name('live_search3.action');

Route::post('/createdirec', 'HomeController@createDireccion');

Route::post('/createfactura', 'ConfirmacionController@createFactura');

Route::get('/listcentros', 'TestController@centroventa');
Route::get('/listcentros?CITY={id}', 'TestController@centroventa2');

Route::get('/search', 'SearchController@show');
Route::get('/products/json', 'SearchController@data');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/homePendiente/{id}', 'HomeController@homePendiente');
Route::post('/CancelHomePendiente/{id}', 'HomeController@updateHomePedidoCancelado');
Route::post('/RefreshHomePendiente/{id}', 'HomeController@updateHomePedidoRefresh');
Route::get('/homeedit/{id}/{id2}', 'HomeController@editprod');
Route::post('/updateCarrito/{id}', 'HomeController@updateCarrito'); // update home
Route::delete('/deleteDetalle', 'HomeController@destroyEdit'); // form eliminar

Route::get('/private', 'HomeController@private')->name('private');
Route::get('/users', 'HomeController@users')->name('users');
Route::get('/usersAdmin', 'HomeController@usersAdmin')->name('usersAdmin');
Route::get('/modificarUsuario', 'HomeController@ChangeUser'); //  home  
Route::post('/modificarUsuario/{id}/editUser', 'HomeController@updateUser'); // actualizar

Route::get('/creditouser', 'HomeController@CreditUser'); //  credito del usuario 


Route::get('/products/{id}/{idCentroDeVenta}', 'ProductController@show');
Route::get('/categories/{category}', 'CategoryController@show');

Route::post('/cart', 'CartDetailController@store');
Route::delete('/cart/{id}', 'CartDetailController@destroy');

Route::post('/order/{id}', 'CartController@update');
Route::post('/Authorder/{id}/{idcvta}', 'AuthPedido@updatePedido'); // listado
Route::post('/Cancelorder/{id}', 'AuthPedido@updatePedidoCancelado'); // listado
Route::post('/CancelorderCancelacion/{id}', 'AuthPedido@updatePedidoCanceladoConMotivo'); // listado
Route::post('/CancelorderAuth/{id}', 'AuthPedido@updatePedidoCanceladoAuth'); // listado
Route::post('/Confirmorder/{id}', 'AuthPedido@updatePedidoConfirmado'); // listado

//New chat Online Erzu

Route::get('/chatOnline', 'ChatOnlineController@index')->name('chatOnline');
Route::get('/message/{id}', 'ChatOnlineController@getMessage')->name('message');
Route::post('/message', 'ChatOnlineController@sendMessage');

//Fin New chat Online


Route::get('/private-messages/{user}', 'MessageController@privateMessages')->name('privateMessages');
Route::post('/private-messages/{user}', 'MessageController@sendPrivateMessage')->name('privateMessages.store');

Route::get('/confirmacion/show/{id}', 'ConfirmacionController@show'); //
Route::get('/pago/{id}', 'ConfirmacionController@pago')->name('pagar');

Route::post('/procces', 'ProcessController@pagar');
Route::resource('pagar', 'PagoController');

Route::get('/pago', 'ConfirmacionController@index'); //
Route::get('/pagoRechazado', 'ConfirmacionController@pagoRechazado'); //



 	
Route::get('/pruebahome', 'HomeController@prueba');
Route::get('/listadoPedidos', 'pedidoModificadoController@prueba')->name('listado');
Route::get('/confirmado', 'NotificationController@confirmado')->name('confirmado');

Route::get('/pruebaCart', 'CartController@prueba');

Route::post('/updatePedido', 'AdminPedidoController@updatePedido'); // listado  



Route::resource('notificaciones', 'NotificationController');
Route::get('/markAsRead', 'NotificationController@markAsRead')->name('markAsRead'); //
Route::post('/mark-as-read', 'NotificationController@markNotification')->name('markNotification');




Route::middleware(['auth', 'admin'])->prefix('admin')->namespace('Admin')
->group(function () {
	


	Route::get('/correosusers', 'AdminPedidoController@correosusers'); // listado
	Route::post('/correosusers/modificar/{iduser}', 'AdminPedidoController@updateusercorreo');
	Route::get('/productosactivos', 'AdminPedidoController@productosactivos')->name('productos'); // listado
	Route::get('/StatusProducto', 'AdminPedidoController@UpdateStatusProduct')->name('StatusProducto');
	//Update img por codigo
	Route::get('/updateImgProducto', 'AdminPedidoController@UpdateImgProducto')->name('updateImgProducto');
	//Update usuarios oralce
	Route::post('/updateUserOracle', 'AdminPedidoController@updateUserOracle')->name('updateUserOracle');

	
	Route::get('/precios', 'AdminPedidoController@listprice'); // listado
	
    Route::get('/preciosfiltrados', 'AdminPedidoController@listpricefilter1');
    Route::get('/precios/{id}/edit', 'AdminPedidoController@listpricefilter'); //
//	Route::post('/precios/{id}/{id2}/update', 'AdminPedidoController@UpdatePrecios');
    Route::post('/precios/{id}/update', 'AdminPedidoController@UpdatePrecios');

    Route::get('/centrodeventas', 'AdminPedidoController@listcentros'); // listado
    Route::get('/centrodeventas/{id}/edit', 'AdminPedidoController@editcentros'); //
 	Route::get('/centrodeventas/add', 'AdminPedidoController@listcentrosAdd'); // listado
	Route::post('/insertcentroventas', 'AdminPedidoController@createcentro');
	Route::post('/centrodeventas/{id}/update', 'AdminPedidoController@UpdateCentros');


Route::get('/promolist', 'AdminPedidoController@userpromociones'); // listado
Route::get('/promo/{id}', 'AdminPedidoController@asignarpromo'); // 
Route::get('/tiempoentrega', 'AdminPedidoController@tiempoentrega'); // 

    Route::get('/PedidosUsuario','AdminPedidoController@getUsers');
	Route::get('/ReportesPedidos','ReportesController@getPedidosDia');
	Route::get('/ReporteGeneral','ReportesController@getReporteGeneral')->name('searchMonto');
	Route::get('/getBuscarMonto', 'ReportesController@getBuscarMonto'); 

	Route::get('/ReportesPedidosFactura','FacturaController@getFechaFactura');
	Route::get('/newuser', 'AdminPedidoController@newuser'); // listado
	Route::get('/newuserejecutivo', 'AdminPedidoController@newuseroracleEjecutivo'); // listado
	Route::post('/asignarRuta/{id}', 'AdminPedidoController@asignarRuta'); // 


});
Route::middleware(['auth', 'gester'])->prefix('gester')->namespace('Admin')
->group(function () {

Route::get('/products', 'ProductController@index'); // listado
	Route::get('/products/create', 'ProductController@create'); // formulario
	Route::post('/products', 'ProductController@store'); // registrar
	Route::get('/products/{id}/edit', 'ProductController@edit'); // formulario edición
	Route::post('/products/{id}/edit', 'ProductController@update'); // actualizar
	Route::delete('/products/{id}', 'ProductController@destroy'); // form eliminar
	

	Route::get('/products/{id}/images', 'ImageController@index'); // listado
	Route::post('/products/{id}/images', 'ImageController@store'); // registrar
	Route::delete('/products/{id}/images', 'ImageController@destroy'); // form eliminar	
	Route::get('/products/{id}/images/select/{image}', 'ImageController@select'); // destacar

	Route::get('/categories', 'CategoryController@index'); // listado
	Route::get('/categories/create', 'CategoryController@create'); // formulario
	Route::post('/categories', 'CategoryController@store'); // registrar
	Route::get('/categories/{category}/edit', 'CategoryController@edit'); // formulario edición
	Route::post('/categories/{category}/edit', 'CategoryController@update'); // actualizar
	Route::delete('/categories/{category}', 'CategoryController@destroy'); 




});

Route::middleware(['auth', 'useradmin'])->prefix('useradmin')->namespace('Admin')
->group(function () {



Route::get('/newuser', 'AdminPedidoController@newuser'); // listado

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    protected $table = "products";
    protected $primaryKey = 'id';

//Query Scope

public function scopeName($query, $name)
{
    if($name)
        return $query->where('name', 'LIKE', "%$name%");
}

public function scopeCodigo($query, $codigo)
{
    if($codigo)
        return $query->where('codigo', 'LIKE', "%$codigo%");
}

public function scopeCity($query, $city)
{
    if($city)
        return $query->where('organization_id', 'LIKE', "%$city%");
}

public function scopeJoinCity($query,$city){

    return $query->leftjoin('citys', 'city.organization_id','products.organization_id');
}

    // $product->category
    public function category()
    {
    	return $this->belongsTo(Category::class);
    }

    // $product->images
    public function images()
    {
    	return $this->hasMany(ProductImage::class);
    }

    public function getFeaturedImageUrlAttribute()
    {
        $featuredImage = $this->images()->where('featured', true)->first();
        if (!$featuredImage)
            $featuredImage = $this->images()->first();

        if ($featuredImage) {
            return $featuredImage->url;
        }

        // default
        return '/images/default.gif';
    }

    public function getCategoryNameAttribute()
    {
        if ($this->category)
            return $this->category->name;

        return 'General';
    }
}

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;
use App\Citys;
use App\DatPrecios;
use App\CentroVenta;
use App\User;

class SearchController extends Controller
{
    public function show(Request $request)
    {   
        $query = $request->input('query');
       
        $id2=1;

        $DatPrecioss = DatPrecios::select('idcentroventa')->where('idcategory', $id2)->orderBy('precios','desc')->get();

        $first = $DatPrecioss->first()->idcentroventa;

        
        $products = DatPrecios::distinct('nameproduct')
        ->leftjoin('product_images', 'dat_precios.idproduct', '=', 'product_images.product_id')
        ->select('dat_precios.nameproduct','dat_precios.idproduct','dat_precios.precios','dat_precios.idcentroventa','product_images.image')
       
        ->where('dat_precios.idcentroventa', $first)
        ->where('dat_precios.nameproduct', 'like', "%$query%")

        ->orderBy('dat_precios.precios','desc')->paginate(20);

        //return $request;
        return view('search.show')->with(compact('products', 'query'));
    }

    public function data()
    {
        $products = Product::pluck('name');
        return $products;
    }
}

resources/views/search/show.blade.php
@extends('layouts.app')

@section('title', 'Resultados de búsqueda')

@section('body-class', 'profile-page')

@section('styles')
    <style>
        .team {
            padding-bottom: 50px;
        }
        .team .row .col-md-4 {
            margin-bottom: 5em;
        }
        .team .row {
          display: -webkit-box;
          display: -webkit-flex;
          display: -ms-flexbox;
          display:         flex;
          flex-wrap: wrap;
        }
        .team .row > [class*='col-'] {
          display: flex;
          flex-direction: column;
        }
        #selectciudad{
            display: none;
        }
        #shoppingcar{
            display: none;
        }
         #namess{
            display: none;
        }
         #imagess{
            display: none;
        }
  #menusuperior {
    display:block;
    width:100%;
    background:#242424;
    height: 90px;
    text-align: right;
  
    padding-top: 30px;

  }
@media (min-width: 540px) {
  .mensajes_para_usuarios{
    display: none;
  }
    </style>
@endsection

@section('content')

<div class="main main-raised"style="background-color: #fff;-webkit-box-shadow: 0px 0px 50px 38px rgba(255,255,255,1);
-moz-box-shadow: 0px 0px 50px 38px rgba(255,255,255,1);
box-shadow: 0px 0px 50px 38px rgba(255,255,255,1);">

    <div class="profile-content">
        
        <div class="container">
            <h5 class="mensajes_para_usuarios" style="color: #FE8A29; font-size: 14px;position: relative;font-style: italic;font-weight: 600;font-family:Consolas;margin-bottom: -2%;">Esta aplicacion es para uso escusivo de negocios</h5>
<h5 class="mensajes_para_usuarios" style="color: #FF0000; font-size: 14px;position: relative;font-style: italic;font-weight: 600;font-family:Consolas;margin-bottom: 0%;">Pedidos mas allá de las 12 de la tarde ya no aplican para el día de mañana</h5>
            <div class="row">
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <div class="profile">
                    <div class="avatar">
                        <img src="/img/search.png" alt="Imagen de una lupa que representa a la página de resultados" class="img-circle img-responsive img-raised">
                    </div>

                    <div class="name">
                        <h3 class="title">Resultados de búsqueda</h3>
                    </div>

                    
                    @if (session('notification'))
                        <div class="alert alert-success">
                            {{ session('notification') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="description text-center">
                <p>Se encontraron {{ $products->count() }} resultados para el término {{ $query }}.</p>
            </div>

            <div class="team text-center">
                <div class="row">
                    @foreach ($products as $product)
                    <div class="col-md-4">
                        <div class="team-player">

@if (Auth::check())

@if(is_null($product->image))
   <a  href="{{ url('/products/'.$product->idproduct.'/'.$product->idcentroventa) }}"> <img src=" {{ $product->featured_image_url }}" alt="Thumbnail Image" class="img-raised img-circle"></a>
@else 
<a  href="{{ url('/products/'.$product->idproduct.'/'.$product->idcentroventa) }}"> <img src="{{ asset('images/products/'.$product->image) }}" alt="Thumbnail Image" class="img-raised img-circle"></a>
@endif

@else
@if(is_null($product->image))
<a href="/login"><img src=" {{ $product->featured_image_url }}" alt="Thumbnail Image" class="img-raised img-circle"></a>
@else 
<a href="/login"><img src="{{ asset('images/products/'.$product->image) }}" alt="Thumbnail Image" class="img-raised img-circle"></a>
@endif
@endif
@if (Auth::check())
 <h4 class="title">
    <a href="{{ url('/products/'.$product->idproduct.'/'.$product->idcentroventa) }}">{{ $product->nameproduct }}</a>
 </h4>
@else
 <h4 class="title">
    <a href="/login">{{ $product->nameproduct }}</a>
 </h4>
@endif


                        
                            
                        </div>
                    </div>
                    @endforeach
                </div>
                <div class="text-center">
                    {{ $products->links() }}
                </div>
            </div>

        </div>
    </div>
</div> 

@include('includes.footer')
@endsection